name: Azure MCP - Service Onboarding Request
description: Request for a new service / tool for the Azure MCP server.
title: "[ONBOARD]"
labels: ["onboarding","needs-triage","Azure.Mcp.Server"]
projects: ["Microsoft/1976"]

body:
  - type: markdown
    attributes:
      value: |
        > ⚠️ If you are a Microsoft employee then please review our [Azure Internal Onboarding Documentation](https://aka.ms/azmcp/intake).
  - type: input
    id: library
    attributes:
      label: Service / Tool Name
      description: Name and description of the Azure service or tool you want to onboard.
      placeholder: ex. Azure.Storage.Blobs
    validations:
      required: true
  - type: input
    id: contacts
    attributes:
      label: Contacts
      description: List of contacts who own the Service / Tool being onboarded
      placeholder: ex. Alice Cooper (alcoop), Bob Dylan (bdylan)
    validations:
      required: true
  - type: textarea
    id: scenarios
    attributes:
      label: Intended Agent Scenarios
      description: What customer scenarios are you trying to solve with this service or tool? Please provide a brief description of the scenarios and how they relate to the Azure MCP server.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: November 2025, February 2026, TBD, etc.
        Please provide your desired timeline
      placeholder: TBD
    validations:
      required: true
