parameters:
- name: VsixTargets
  type: object
- name: ServerName
  type: string
- name: IncludeNative
  type: boolean
- name: SkipDockerRelease
  type: boolean

jobs:
- job: TagRepository
  displayName: "Create release tag"
  condition: and(succeeded(), ne(variables['Skip.TagRepository'], 'true'))
  steps:
  - checkout: self

  - download: current
    displayName: Download npm_$(PipelineArtifactName)_packed
    artifact: npm_$(PipelineArtifactName)_packed

  - template: /eng/common/pipelines/templates/steps/retain-run.yml

  - pwsh: |
      $serverName = '${{ parameters.ServerName }}'
      $versionSuffix = $env:VERSIONSUFFIX
      $version = ./eng/scripts/Get-Version.ps1 -ServerName $serverName
      $tag = "$serverName-$version$versionSuffix"

      gh release create $tag --title "$serverName $version$versionSuffix"
      gh release upload $tag $(Pipeline.Workspace)/npm_$(PipelineArtifactName)_packed/*/*/*.tgz
    displayName: Create GitHub Release and upload artifacts
    env:
      GH_TOKEN: $(azuresdk-github-pat)

- template: /eng/pipelines/templates/jobs/npm/release-npm.yml
  parameters:
    ServerName: ${{ parameters.ServerName }}
    IncludeNative: ${{ parameters.IncludeNative }}
    DependsOn: TagRepository

- template: /eng/pipelines/templates/jobs/nuget/release-nuget.yml
  parameters:
    ServerName: ${{ parameters.ServerName }}
    DependsOn: TagRepository

- template: /eng/pipelines/templates/jobs/vsix/release-vsix.yml
  parameters:
    ServerName: ${{ parameters.ServerName }}
    VsixTargets: ${{ parameters.VsixTargets }}
    DependsOn: TagRepository


- ${{ if ne(parameters.SkipDockerRelease, 'true') }}:
  - template: /eng/pipelines/templates/jobs/docker/release-docker.yml
    parameters:
      ContainerRegistry: 'azuresdkimages'
      DeploymentEnvironment: 'public'
      ServerName: ${{ parameters.ServerName }}
      DependsOn: TagRepository

- job: UpdatePackageVersion
  displayName: "Update Package Versions"
  condition: and(succeeded(), ne(variables['Skip.UpdatePackageVersion'], 'true'))
  dependsOn: TagRepository
  steps:
  - checkout: self

  # Apply the version increment to each library, which updates the Cargo.toml and changelog files.
  - task: PowerShell@2
    displayName: Increment version
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)/eng/scripts/Update-Version.ps1
      arguments: >
        -ServerName '${{ parameters.ServerName }}'

  - template: /eng/common/pipelines/templates/steps/create-pull-request.yml
    parameters:
      PRBranchName: increment-package-version-$(Build.BuildId)
      CommitMsg: "Increment package version after release"
      PRTitle: "Increment version after release"
      RepoOwner: microsoft
      # For CloseAfterOpenForTesting, create-pull-request.yml expects a bool as a string  and adds `$` to the front for
      # powershell. We pass an environment variable reference and omit the `$`
      CloseAfterOpenForTesting: env:SETDEVVERSION
