parameters:
- name: ServerName
  type: string
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: Sign
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  pool: # Binary signing of mac bits needs to happen on mac see https://github.com/Azure/azure-mcp/blob/4ff032fafc77bc618738879b7028665c0de2e632/eng/scripts/Compress-ForSigning.ps1#L40
    name: $(MACPOOL)
    vmImage: $(MACVMIMAGE)
    os: macos
  steps:
  - checkout: self

  - download: current
    displayName: Download artifacts

  - task: Powershell@2
    displayName: "Stage files for signing"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Compress-ForSigning.ps1
      arguments: >
        -ArtifactsPath '$(Pipeline.Workspace)'
        -ArtifactPrefix '$(PipelineArtifactName)_'
        -OutputPath '$(Build.ArtifactStagingDirectory)/signed'

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-230012' # MS Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed
      BinaryPattern: |
        **/win-*/**/azmcp.dll
        **/win-*/**/azmcp.exe
        **/win-*/**/mcptmp.dll
        **/win-*/**/mcptmp.exe
        **/win-*/**/*.Mcp.*.dll

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-231522' # MS 3rd Party Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed
      BinaryPattern: |
        **/win-*/**/ModelContextProtocol*.dll
        **/win-*/**/Newtonsoft.Json.dll
        **/win-*/**/Npgsql.dll
        **/win-*/**/OpenAI.dll
        **/win-*/**/OpenTelemetry*.dll
        **/win-*/**/YamlDotNet.dll

  - template: pipelines/steps/azd-cli-mac-signing.yml@azure-sdk-build-tools
    parameters:
      MacPath: $(Build.ArtifactStagingDirectory)/signed
      MacPattern: "**/*.zip"

  - task: Powershell@2
    displayName: "Expand Mac executables after signing"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Expand-AfterSigning.ps1
      arguments: >
        -Path '$(Build.ArtifactStagingDirectory)/signed'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/signed
      ArtifactName: $(PipelineArtifactName)_signed
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

- job: Verify_Signing
  displayName: "Verify Signing"
  dependsOn: Sign
  pool:
    name: $(WINDOWSPOOL) # Signing verification must happen on windows
    image: $(WINDOWSVMIMAGE)
    os: windows
  variables:
  - template: /eng/pipelines/templates/variables/image.yml
  - template: /eng/pipelines/templates/variables/globals.yml
  steps:
  - checkout: none

  - download: current
    artifact: $(PipelineArtifactName)_signed
    displayName: "Download signed MCP server binaries"

  - pwsh: |
      Write-Host "Verifying binary signing for win-x64 and win-arm64 binaries..."
      $allSigned = $true
      $signedBinaries = Get-ChildItem -Path '$(Pipeline.Workspace)/$(PipelineArtifactName)_signed/**/win-*' -Recurse -Include @("*.dll", "*.exe")
      foreach ($binary in $signedBinaries) {
          if ((Get-AuthenticodeSignature -FilePath $binary.FullName).Status -ne 'Valid') {
              Write-Host "Binary $($binary.FullName) is NOT signed correctly."
              $allSigned = $false
          }
          else {
              Write-Host "Binary $($binary.FullName) is signed correctly."
          }
      }
      if (-not $allSigned) {
          Write-Error "One or more binaries are not signed correctly."
          exit 1
      }
    displayName: "Verify Binary Signing"

- template: /eng/pipelines/templates/jobs/npm/pack-npm.yml
  parameters:
    DependsOn: Sign

- template: /eng/pipelines/templates/jobs/nuget/pack-and-sign-nuget.yml
  parameters:
    DependsOn: Sign

- template: /eng/pipelines/templates/jobs/vsix/pack-and-sign-vsix.yml
  parameters:
    DependsOn: Sign
    ServerName: ${{ parameters.ServerName }}
